Repository f-lab-edu/fream, pull requests merged in 2022-01, with the labels that each got.

#46 github actions 제거
  .github/workflows/check_main.yml
  .github/workflows/ci.yml
Labels: devops

#47 통합 테스트 제거
  build.gradle
  githooks/pre-commit
  src/integrationTest/groovy/kr/flab/fream/AuctionIntegrationSpec.groovy
  src/integrationTest/groovy/kr/flab/fream/BaseIntegrationSpec.groovy
  src/integrationTest/groovy/kr/flab/fream/DatabaseTest.groovy
  src/integrationTest/groovy/kr/flab/fream/ProductionIntegrationSpec.groovy
  src/integrationTest/resources/application-local.yml
  src/integrationTest/resources/application-test.yml
  src/integrationTest/resources/application.yml
  src/integrationTest/resources/db/mysql/conf.d/my.cnf
  src/test/groovy/kr/flab/fream/IntegrationSpec.groovy
  src/test/groovy/kr/flab/fream/controller/auction/AuctionControllerSpec.groovy
  src/test/groovy/kr/flab/fream/controller/product/ProductControllerSpec.groovy
  src/test/groovy/kr/flab/fream/domain/auction/service/AuctionServiceIntegrationSpec.groovy
  src/test/groovy/kr/flab/fream/domain/auction/service/AuctionServiceSpec.groovy
  src/test/groovy/kr/flab/fream/domain/product/model/CategorySpec.groovy
  src/test/groovy/kr/flab/fream/domain/product/service/ProductServiceIntegrationSpec.groovy
  src/test/groovy/kr/flab/fream/mybatis/mapper/auction/AuctionMapperSpec.groovy
  src/test/groovy/kr/flab/fream/mybatis/mapper/product/ProductMapperSpec.groovy
Labels: refactoring

#44 37 user login
  src/main/java/kr/flab/fream/auth/AbstractAuthenticationResolver.java
  src/main/java/kr/flab/fream/auth/AuthenticationResolver.java
  src/main/java/kr/flab/fream/config/WebConfig.java
  src/main/java/kr/flab/fream/controller/GlobalExceptionHandler.java
  src/main/java/kr/flab/fream/controller/user/LoginDto.java
  src/main/java/kr/flab/fream/controller/user/UserController.java
  src/main/java/kr/flab/fream/controller/user/UserDto.java
  src/main/java/kr/flab/fream/domain/auction/service/AuctionService.java
  src/main/java/kr/flab/fream/domain/user/model/Address.java
  src/main/java/kr/flab/fream/domain/user/model/User.java
  src/main/java/kr/flab/fream/domain/user/service/UserService.java
  src/main/java/kr/flab/fream/interceptor/LoginInterceptor.java
  src/main/java/kr/flab/fream/mybatis/mapper/user/UserMapper.java
  src/main/resources/application-local.yml
  src/main/resources/db/migration-seed/V1.3.1__User_seed.sql
  src/main/resources/kr/flab/fream/mybatis/mapper/auction/AuctionMapper.xml
  src/main/resources/kr/flab/fream/mybatis/mapper/user/UserMapper.xml
  src/test/groovy/kr/flab/fream/auth/AuthenticationResolverTest.groovy
  src/test/groovy/kr/flab/fream/controller/auction/AuctionControllerSpec.groovy
  src/test/groovy/kr/flab/fream/controller/product/ProductControllerSpec.groovy
  src/test/groovy/kr/flab/fream/controller/user/UserControllerSpec.groovy
  src/test/groovy/kr/flab/fream/domain/user/service/UserServiceSpec.groovy
  src/test/groovy/kr/flab/fream/mybatis/mapper/user/UserMapperSpec.groovy
  src/test/resources/application-local.yml
  src/test/resources/application-test.yml
Labels: feature

#49 22 sign up member
  build.gradle
  src/main/java/kr/flab/fream/config/WebConfig.java
  src/main/java/kr/flab/fream/controller/user/UserController.java
  src/main/java/kr/flab/fream/domain/user/model/User.java
  src/main/java/kr/flab/fream/domain/user/service/UserService.java
  src/main/java/kr/flab/fream/util/BcryptHelper.java
  src/main/java/kr/flab/fream/util/EncryptHelper.java
  src/main/resources/kr/flab/fream/mybatis/mapper/user/UserMapper.xml
  src/test/groovy/kr/flab/fream/controller/user/UserControllerSpec.groovy
  src/test/groovy/kr/flab/fream/domain/user/service/UserServiceSpec.groovy
  src/test/groovy/kr/flab/fream/util/EncryptHelperSpec.groovy
Labels: feature

#51 컨테이너 이미지 빌드
  Dockerfile
  build.gradle
Labels: build, devops

#52 CD 스크립트 작성
  .gitignore
  deployment/Jenkinsfile-cd
  deployment/Jenkinsfile-pr
  deployment/infra/000-install-packages.sh
  deployment/infra/010-setup-infra.sh
  deployment/infra/020-deploy-fream.sh
  deployment/infra/conf/mysql/conf.d/my.cnf
  deployment/infra/conf/nginx/fream.conf
  deployment/infra/destroy.sh
  deployment/infra/load-envs.sh
Labels: build, devops
