Repository f-lab-edu/fream, pull requests merged in 2022-02, with the labels that each got.

#55 프로덕션 배포 환경 수정 사항 적용
  deployment/infra/conf/nginx/service-url.inc
  src/main/resources/application-prod.yml
Labels: devops

#60 [v2] EFK 스택 docker compose에 추가
  docker-compose.yml
  fluentd/Dockerfile
  fluentd/conf/fluent.conf
  product-service/src/main/java/kr/flab/fream/productservice/ProductController.java
Labels: build, devops

#62 build:스프링세션 라이브러리 추가
  build.gradle
Labels: bug, build
